{
 "title": "Custom Backup Status Dashboard",
 "tags": [
  "backup",
  "custom"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_ip",
    "query": {
     "query": "label_values(custom_backup_info, server_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "custom_backup_archive_size_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "custom_backup_info", "legendFormat": "__auto" },
    {
     "expr": "custom_backup_job_duration_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - custom_backup_last_success_timestamp_seconds",
     "legendFormat": "__auto"
    },
    { "expr": "custom_backup_job_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "custom_backup_job_duration_seconds",
     "legendFormat": "{{server_ip}}"
    }
   ]
  },
  {
   "title": "Backup Archive Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "custom_backup_archive_size_bytes",
     "legendFormat": "{{server_ip}}"
    }
   ]
  },
  {
   "title": "last runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - custom_backup_last_success_timestamp_seconds",
     "legendFormat": "{{server_ip}}"
    }
   ]
  }
 ]
}